### ISSUE TITLE
Improve witness testing feedback and documentation

### ISSUE THREAD

**Issue by Brianspha** [dl-solarity/zkit#14]
### Description:
I've encountered an issue with the witness testing process in zkit. Currently, there's a lack of clear feedback when running tests, which makes it difficult to determine if tests have passed or failed.

### Current Behavior:
- There's no output related to test results when running `npx hardhat zkit make`.
- Even when asserting false in a test file, the console doesn't indicate a failed test.

### Expected Behavior:
- Clear console output indicating whether tests have passed or failed.
- Detailed error messages for failed assertions.
- Documentation or examples showing how to interpret test results.

### Steps to Reproduce:
1. Create a test file with an intentionally failing assertion.
2. Run `npx hardhat zkit make`.
3. Observe the lack of feedback about the failed test.

### Example 
```typescript
import { zkit } from "hardhat"; // hardhat-zkit plugin
import { expect } from "chai"; // chai-zkit extension
import { IntergerDivision } from "@zkit"; // zktype circuit-object
async function main() {
  const circuit: IntergerDivision = await zkit.getCircuit("circuits/interger_division.circom:IntergerDivision");
  await expect(circuit)
    .with.witnessInputs({ a: "4", b: "2" })
    .to.have.witnessOutputs({ c: "2" });
  const proof = await circuit.generateProof({ a: "4", b: "2" });
  expect(await circuit.verifyProof(proof)).to.be.false; //@dev here it should fail because the results are true
}

main()
  .then()
  .catch((e) => console.log(e));
```

**Comment by Arvolear** [comment]
Hey, @Brianspha, `npx hardhat zkit make` command only launches circuits compilation and generation of `zkeys`. In order to run the test, you need to execute it through hardhat separately. Use `npx hardhat run <your file>` or `npx hardhat test` if you are using mocha.

**Comment by Arvolear** [comment]
Clarified the plugin usage section in [hardhat-zkit readme](https://github.com/dl-solarity/hardhat-zkit/commit/73d5c15e66d679b98b1955ea99523d3676c48ffd).
